services:
  backend-python:
    build:
      context: ./api
    container_name: backend-python
    ports:
      - "5000:5000"
    depends_on:
      - db

  backend-express:
    build:
      context: ./server
    container_name: backend-express
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend-react:
    build:
      context: ./client
    container_name: frontend-react
    ports:
      - "80:5173"
    depends_on:
      - backend-python
      - backend-express

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${SET_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${DB_NAME:-db_social_friendly}"
      MYSQL_USER: "${DB_USER:-test}"
      MYSQL_PASSWORD: "${DB_PASS:-test}"
    volumes:
      - ./db:/home/
    command: mysqld --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

volumes:
  mysql_data:
    driver: local
